import React from "react";
import "../App.css";


export const PolicyOne = () => {
	let setColor = { fontsize: "50px", color: "palevioletred" }
	return (
		<div className="policy">
			<h3 style={setColor}>Privacy</h3>
			<br /><br /><br /><br />We value the trust you place in us and recognize the importance of secure transactions and information privacy.
			This Privacy Policy describes how FlowersParadise Internet Private Limited and its affiliates collect, use, share or otherwise process your personal information through this website.

		</div>
	);
};

export const PolicyTwo = () => {
	let setColor = { fontsize: "50px", color: "palevioletred" }
	return (
		<div className="policy">
			<h3 style={setColor}>Return</h3>
			<br /><br /><br /><br />Returns is a scheme provided by respective sellers directly under this policy in terms of which the option of exchange, replacement and/ or refund is offered by the respective sellers to you. All products listed under a particular category may not have the same returns policy.
			For all products, the returns/replacement policy provided on the product page shall prevail over the general returns policy.

		</div>
	);
};

export const PolicyThree = () => {
	let setColor = { fontsize: "50px", color: "palevioletred" }
	return (
		<div className="policy">
			<h3 style={setColor}>Terms </h3>
			<br /><br /><br /><br />This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000.
			This electronic record is generated by a computer system and does not require any physical or digital signatures.

		</div>
	);
};

